config/routes.rb
Rails.application.routes.draw do
  resources :recettes
  get 'home/index'
  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recette.rb
class Recette < ApplicationRecord
  belongs_to :utilisateur 
end

app/models/utilisateur.rb
class Utilisateur < ApplicationRecord
has_many :recettes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/recettes_controller.rb
class RecettesController < ApplicationController
  before_action :set_recette, only: [:show, :edit, :update, :destroy]

  # GET /recettes
  # GET /recettes.json
  def index
    @recettes = Recette.all
  end

  # GET /recettes/1
  # GET /recettes/1.json
  def show
  end

  # GET /recettes/new
  def new
    @recette = Recette.new
  end

  # GET /recettes/1/edit
  def edit
  end

  # POST /recettes
  # POST /recettes.json
  def create
    @recette = Recette.new(recette_params)

    respond_to do |format|
      if @recette.save
        format.html { redirect_to @recette, notice: 'Recette was successfully created.' }
        format.json { render :show, status: :created, location: @recette }
      else
        format.html { render :new }
        format.json { render json: @recette.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recettes/1
  # PATCH/PUT /recettes/1.json
  def update
    respond_to do |format|
      if @recette.update(recette_params)
        format.html { redirect_to @recette, notice: 'Recette was successfully updated.' }
        format.json { render :show, status: :ok, location: @recette }
      else
        format.html { render :edit }
        format.json { render json: @recette.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recettes/1
  # DELETE /recettes/1.json
  def destroy
    @recette.destroy
    respond_to do |format|
      format.html { redirect_to recettes_url, notice: 'Recette was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recette
      @recette = Recette.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recette_params
      params.require(:recette).permit(:nom, :photo,:createur,:description,:prix,:complexite,:temps_preparation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/recettes_helper.rb
module RecettesHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Testpostgre" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

<!--     <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Testpostgre</a>
<!--         <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Link1", "/path1"  %></li>
            <li><%= link_to "Link2", "/path2"  %></li>
            <li><%= link_to "Link3", "/path3"  %></li>
          </ul>
        </div> -->
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
<!--           <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well --> 

      </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2016</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/recettes/_form.html.erb
<%= form_for @recette, :html => { :class => "form-horizontal recette" } do |f| %>

  <% if @recette.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@recette.errors.count, "error") %> prohibited this recette from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @recette.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :nom, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :nom, :class => 'form-control' %>
    </div>
    <%=f.error_span(:nom) %>
  </div>

  <div class="form-group">
    <%= f.label :photo, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :photo, :class => 'form-control' %>
    </div>
    <%=f.error_span(:photo) %>
  </div>
  <div class="form-group">
    <%= f.label :createur, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :createur, :class => 'form-control' %>
    </div>
    <%=f.error_span(:createur) %>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :prix, :class => 'form-control' %>
    </div>
    <%=f.error_span(:description) %>
  </div>
  <div class="form-group">
    <%= f.label :prix, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :prix, :class => 'form-control' %>
    </div>
    <%=f.error_span(:prix) %>
  </div>
  <div class="form-group">
    <%= f.label :complexite, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :complexite, :class => 'form-control' %>
    </div>
    <%=f.error_span(:complexite) %>
  </div>
  <div class="form-group">
    <%= f.label :temps_preparation, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :temps_preparation, :class => 'form-control' %>
    </div>
    <%=f.error_span(:temps_preparation) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                recettes_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/recettes/edit.html.erb
<%- model_class = Recette -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/recettes/index.html.erb
<%- model_class = Recette -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:nom) %></th>
      <th><%= model_class.human_attribute_name(:photo) %></th>
      <th><%= model_class.human_attribute_name(:createur) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:prix) %></th>
      <th><%= model_class.human_attribute_name(:complexite) %></th>
      <th><%= model_class.human_attribute_name(:temps_preparation) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @recettes.each do |recette| %>
      <tr>
        <td><%= link_to recette.id, recette_path(recette) %></td>
        <td><%= recette.nom %></td>
        <td><img src="<%= recette.photo %>" style="width:300px" /></td>
        <td><%= recette.createur %></td>
        <td><%= recette.description %></td>
        <td><%= recette.prix %></td>
        <td><%= recette.complexite %></td>
        <td><%= recette.temps_preparation %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_recette_path(recette), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      recette_path(recette),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_recette_path,
            :class => 'btn btn-primary' %>

app/views/recettes/new.html.erb
<%- model_class = Recette -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/recettes/show.html.erb
<%- model_class = Recette -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:nom) %>:</strong></dt>
  <dd><%= @recette.nom %></dd>
  <dt><strong><%= model_class.human_attribute_name(:photo) %>:</strong></dt>
  <dd><%= @recette.photo %></dd>
  <dt><strong><%= model_class.human_attribute_name(:createur) %>:</strong></dt>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dt><strong><%= model_class.human_attribute_name(:prix) %>:</strong></dt>
  <dt><strong><%= model_class.human_attribute_name(:complexite) %>:</strong></dt>
  <dt><strong><%= model_class.human_attribute_name(:temps_preparation) %>:</strong></dt>

  <dd><%= @recette.createur %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              recettes_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_recette_path(@recette), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              recette_path(@recette),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>